### ISSUE TITLE
[변경] file_result.html 결과값을 최신순부터 보여주기

### ISSUE THREAD

**Issue by auberr** [kbm1933/B2_IIEII_ML#11]
https://github.com/kbm1933/B2_IIEII_ML/blob/77922f078ebb76a8934b495f1c3889c1c6afdeca/community/templates/file_result.html#L20

결과 값을 최신 순으로 보여주면 어떨까요?
아래와 같이 html 에서 변경해주면 어떨까요?

`{% for file in files reversed %}`

**Comment by DongIkkk** [comment]
좋습니다 최신순을 생각 못하고 있었네요 
DTL로 역순을 만들어주는 것도 좋지만 views 에서 파이썬으로 역순으로 만들어진 데이터를 주는게 더 좋을 것 같습니다!

**Comment by wonprogrammer** [comment]
views.py/file_result함수에서 YoloResult object  불러올때 ".order_by('-id')" 붙여주니 업로드 최신 순으로 잘 나옵니다!
