### ISSUE TITLE
[에러] base.html 내 logout 링크

### ISSUE THREAD

**Issue by auberr** [kbm1933/B2_IIEII_ML#18]
https://github.com/kbm1933/B2_IIEII_ML/blob/7ba1f82bd93e86524fe13ea38a2ea904ad130e85/users/templates/base.html#L26

`<a class="nav-link" href="/logout"> 로그아웃 </a>`

혹은

`<a class="nav-link" href="{% users:logout %}"> 로그아웃 </a>`

로 변경되어야 합니다.

**Comment by uniqquej** [comment]
여기 부분 signup.html이랑 같이 수정해서 pr했습니다! 작동이 안되나요?

**Comment by auberr** [comment]
앗 확인했습니다. 해당 머지 풀로 확인해보니 잘 작동합니다! 이슈 닫겠습니다.

#14 Merge 로 해결완료
