### ISSUE TITLE
[에러] file_upload.html 내의 링크

### ISSUE THREAD

**Issue by auberr** [kbm1933/B2_IIEII_ML#8]
https://github.com/kbm1933/B2_IIEII_ML/blob/77922f078ebb76a8934b495f1c3889c1c6afdeca/community/templates/fileupload.html#L27

링크 부분에 오류가 있어서 수정해야 될 것 같습니다.

**Comment by auberr** [comment]
`<a class=“nav-link” href=“{% community:file_result %}”> 지금까지 업로드된 이미지 보러가기 </a></li> `

로 수정하면 어떨까요?

**Comment by DongIkkk** [comment]
지금 이 부분 말고도 링크오류가 몇군데 있는데
아마 혜원님이 맥으로 작성하신 " 이 큰따옴표가 윈도우랑 달라서 나타나는 오류인것 같습니다.
자세히 보면 모양이 다른데 찾아서 수정해야할 것 같아요

**Comment by DongIkkk** [comment]
아 이부분 혜원님이 코드복사하셔서 슬랙으로 주신걸 제가 넣은 부분인데 
그 과정에서 큰따옴표가 바뀐것 같습니다
2군데 있는데 제가 큰따옴표 바꿔놓도록 할게요
